---
title: ""
pagetitle: "Florian Gollnow"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---
<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="academicicons/css/academicons.min.css"/>

## Publications 

Year | Title
:--- | :-------------------------------------------- | 
submitted | **Gollnow, F.**, Federico Cammelli, Carlson, K., Garrett, R., Adoption and market coverage influence the effectiveness of supply chain policies  
submitted | Villoria, N., Garrett, R., Carlson, K., **Gollnow, F.** Leakage is Unlikely to Offset the Benefits of Soybean Zero-Deforestation Commitments in Brazil  
under Review | Hissa, L.B.V., Garcia Marquez, J.R., **Gollnow, F.**, Lakes, T. Enhancing synergies for effective large-scale forest restoration in Mato Grosso, Brazilian Amazon
under Review | Hissa, L.B.V., **Gollnow, F.**, Mueller, H., Lakes, T. Land tenure diversity and forest cover change in a deforestation frontier
under Review | Garrett, R., Grabs, J., Cammelli, F., **Gollnow, F.**, Levy, S. Should PES be used to implement zero-deforestation supply chain policies? The case of soy in the Brazilian Cerrado. 
2021 | Garrett, R., Levy, S., **Gollnow, F.**, Hodel, L., Rueda, X. [Have food supply chain policies improved forest conservation and rural livelihoods? A systematic review](https://doi.org/10.1088/1748-9326/abe0ed). Environmental Research Letters
2021 | Enoguanbhor, E.C., **Gollnow, F.**, Walker, B.B. , Nielsen, J.O., Lakes, T. [Key challenges for land use planning strategies and their environmental assessments in the Abuja city-region](https://doi.org/10.3390/land10050443), Nigeria. Land
2021 | Vijay V., Field, C.R, **Gollnow, F.**, Jones, K.K. [Using internet search data to understand information seeking behavior for health and conservation topics during the COVID-19 pandemic](https://doi.org/10.1016/j.biocon.2021.109078), Biological Conservation 
2020 | Enoguanbhor, E.C., **Gollnow, F.**, Walker, B.B. , Nielsen, J.O., Lakes, T. [Simulating urban land expansion in the context of land use planning in the Abuja city-region, Nigeria](https://doi.org/10.1007/s10708-020-10317-x). Geojournal
2019 | Hissa, L.B.V., Aguiar, A., Camargo, R., Santos de Lima, L., **Gollnow, F.**, Lakes, T. [Regrowing forests contribution to law compliance and carbon storage in private properties of the Brazilian Amazon](https://doi.org/10.1016/j.landusepol.2019.104163). Land Use Policy (88), 104-163
2019 | Enoguanbhor, E.C., **Gollnow, F.**, Nielsen, J.O., Lakes, T., Walker, B.B. [Land Cover Change in the Abuja City-Region, Nigeria: Integrating GIS and Remotely Sensed Data to Support Land Use Planning](https://dx.doi.org/10.3390/su11051313). Sustainability (11), 1313
2019 | Rufin, P., **Gollnow, F.**, Müller, D., Hostert, P. [Synthesizing dam-induced land system change](https://doi.org/10.1007/s13280-018-01144-z). Ambio 48(10), 1183-1194
2018 | **Gollnow, F.**, Hissa, L.B.V., Rufin, P., Lakes, T. [Property-level direct and indirect deforestation for soybean production in the Amazon region of Mato Grosso, Brazil](https://doi.org/10.1016/j.landusepol.2018.07.010). Land Use Policy (78), 377–385
2018 | Schägner, J.P., Brander, L., Paracchini, M.L., Maes, J., **Gollnow, F.**, Bertzky, B. [Spatial dimensions of recreational ecosystem service values: A review of meta-analyses and a combination of meta-analytic value-transfer and GIS](https://doi.org/10.1016/j.ecoser.2018.03.003). Ecosystem Services (31), 395–409
2017 | **Gollnow, F.**, Göpel, J., Hissa, L.B.V., Schaldach, R., Lakes, T. [Scenarios of land-use change in a deforestation corridor in the Brazilian Amazon: Combining two scales of analysis](https://doi.org/10.1007/s10113-017-1129-1). Regional Environmental Change (18), 143–159
2017 | Schaldach, R., Meurer, K.H.E., Jungkunst, H.F., Nendel, C., Lakes, T., **Gollnow, F.**, Göpel, J., Boy, J., Guggenberger, G., Strey, R., Strey, S., Berger, T., Gerold, G., Schönenberg, R., Böhner, J., Schindewolf, M., Latynskiy, E., Hampf, A., Parker, P.S., Sentelhas, P.C. [A model-based assessment of the environmental impact of land-use change across scales in Southern Amazonia](https://doi.org/10.1007/s10113-017-1244-z). Regional Environmental Change (18), 161–173
2017 | Schönenberg, R., Goepel, J., Schaldach, R., **Gollnow, F.**, Lakes, T. [Inter- and transdisciplinary scenario construction to explore future land use options in Southern Amazonia](http://www.jstor.org/stable/26270154). Ecology and Society 22 (3)
2016 | Pinheiro, T.F., Escada, M.I.S., Valeriano, D.M., Hostert, P., **Gollnow, F.**, Müller, H. [Forest Degradation Associated with Logging Frontier Expansion in the Amazon: The BR-163 Region in Southwestern Pará, Brazil](https://doi.org/10.1175/EI-D-15-0016.1). Earth Interactions 20 (17), 1–26
2014 | **Gollnow, F.**, Lakes, T. [Policy change, land use, and agriculture: The case of soy production and cattle ranching in Brazil, 2001 - 2012](https://doi.org/10.1016/j.apgeog.2014.09.003). Applied Geography (55), 203–211

## Invited talks 
Year | Title
:--- | :-------------------------------------------- | 
2019 | **Gollnow, F**. Europas Sojakonsum auf Kosten natürlicher Ökosysteme in Brasilien (The environmental impact of European soybean consumption). Dialogforum Nachhaltigere Eiweißfuttermittel, German Federal Ministry of Food and Agriculture, Berlin, Germany
2019 | **Gollnow, F.**, Carlson, K., Garrett, R. Companies commitments to zero-deforestation targets for forest-risk commodities, Global reach & regional changes to deforestation footprints, at the Natural Resources & Environmental Management Research Seminar Series, University of Hawaii. USA

## Presentations
Year | Title
:--- | :-------------------------------------------- | 
2019 | **Gollnow**, F., Hissa, L.B.V., Rufin, P. Analyzing deforestation leakage following the implementation of the Soy Moratorium in Mato Grosso, Brazil, American Association of Geographers annual Meeting (AAG), Washington D.C., USA
2019 | **Gollnow**, F., Garrett, R., Carlson, K. Potential conservation impact of Zero Deforestation Commitments (ZDCs) in the Brazilian Cerrado, 4th Open Science Meeting of the Global Land Program (GLP), Bern, Switzerland
2019 | Levers, C., Piquer-Rodríguez, M., **Gollnow, F.**, Baumann, M., Gasparri, N.I., Gavier-Pizarro,G.I., le Polain de Waroux,Y., Müller, D.,  Müller, R., Volante, J.,  Kuemmerle T. Scenarios of commodity frontier expansion in the Gran Chaco and their environmental impacts. 4th Open Science Meeting of the Global Land Program (GLP), Bern, Switzerland
2019 | Rivero Castro, R., Carlson, K., Garrett, R., Villoria, N., Levy, S., **Gollnow, F.**. Modeling the effects of soybean sector zero-deforestation commitment implementation on land cover change in South America. 4th Open Science Meeting of the Global Land Program (GLP), Bern, Switzerland
2015 | **Gollnow, F.**, Göpel, J., Lakes, T., Schaldach, R. A Multi-Scale Land Use Modeling approach for the Brazilian Amazon, International Association for Landscape Ecology World Congress (IALE), Portland, USA
2015 | Lakes, T., **Gollnow, F.**, Göpel, J., Schaldach, R. Future development paths of local land use changes within a globally changing world – a Multi-Scale Land Use Modeling approach for the Brazilian Amazon, Deutscher Kongress für Geographie (DKG), Berlin, Germany
2015 | Oeser, J., Santibanez, S., **Gollnow, F.**, Lakes, T., Kloft, M. Maschinelles Lernen zur Modellierung raum-zeitlicher Prozesse, Deutscher Kongress für Geographie (DKG), Berlin, Germany
2014 | **Gollnow, F.**, Lakes, T., 2014. De-spatialization of land use change? Soy expansion and cattle displacement in the Brazilian Amazon, 2nd Global Land Project Open Science Meeting (GLP), Berlin, Germany
2009 | van der Linden, S., Waske, B., Rabe, A., **Gollnow, F.**, Griffiths, P., Kuemmerle, T., Hostert, P. On the use of support vector machines and decision trees in land cover mapping - a review from the user perspective, 3rd Workshop EARSeL SIG Land Use and Land Cover, Bonn, Germany


