---
title: ""
pagetitle: "Florian Gollnow"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---
<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="academicicons/css/academicons.min.css"/>

# Current projects 


### Zero-deforestation commitments
I am interested in the potentials and impacts of zero-deforestation (ZD) commitments for ecosystem conservation and rural livelihoods. This work is 
embedded within the larger ZD research done in collaboration with ETH Zurich @  [zerodeforestationimpacts.com](http://zerodeforestationimpacts.com/). 
I focus on zero deforestation commitments in the Brazilian soybean sector. My main interest is to understand the effectiveness of these commitments on reducing deforestation for commodity expansion. We evaluate ZDs spatial coverage, adoption biases and their combined effect on reducing commodity driven deforestation. To do so, we use spatial and econometric analysis and synthesizes data on commitments, production, trade, land use and land use change.

Year | Title
:--- | :-------------------------------------------- | 
2021 | Garrett, R., Levy, S., **Gollnow, F.**, Hodel, L., Rueda, X. [Have food supply chain policies improved forest conservation and rural livelihoods? A systematic review](https://doi.org/10.1088/1748-9326/abe0ed). Environmental Research Letters
2018 | **Gollnow, F.**, Hissa, L.B.V., Rufin, P., Lakes, T. [Property-level direct and indirect deforestation for soybean production in the Amazon region of Mato Grosso, Brazil](https://doi.org/10.1016/j.landusepol.2018.07.010). Land Use Policy (78), 377–385
  
\
  
### Socioecological transformations in the Republic of Georgia
Georgia’s modern history has been characterized by multiple stark institutional changes. Containing large parts of the Caucasus biome, Georgia is heavily forested and contains high levels of biodiversity and endemism. This research aims to answer how institutional changes and globalization affect land use and land cover change and rural livelihoods. Scenario modeling will evaluate different conservation and development pathways to aid shape environmental policies. 
  
\

# Past projects


### Land-use change and land-use displacement dynamics in Brazil (Ph.D. Theses)
Demands for agricultural commodities are a major threat for some of the most valuable ecosystems in the world. The expansion of the agricultural sector in Brazil, fueled by global demands for soybeans, contributed to the loss of tropical and savanna ecosystems. However, most deforestation was caused by pastures, raising concerns about land use displacement processes between soybean expansion and cattle ranching. Promising, reductions of deforestation were observed following the implementation of governmental strategies and zero-deforestation supply chain commitments. This thesis aims to contribute to the understanding of spatial and temporal dynamics of soybean expansion and cattle ranching, driving deforestation in one of the most dynamic agricultural expansion and deforestation frontier of Brazil, in Mato Grosso and Pará. In this region, land use displacement describes the conversion of pasture to soybean followed by deforestation for cattle ranching at another location. This process was assessed at regional and property-level. Moreover, scenario analysis was applied to identify regional and subregional dynamics of land use changes. The results indicated that environmental governance affected regional and local land use dynamics and displacement processes. Distal displacement processes between soybean expansion and deforestation were significant, contributing to deforestation, but declined subsequently to the implementation of environmental policies. Likewise, deforestation at property-level declined following the policy implementations. However, the effectiveness of the zero-deforestation supply chain commitment was found to be at risk due to property-level displacement deforestation. Additionally, the scenario analysis emphasized the importance of subregional dynamics and identified risks of future deforestation. Integrating efforts between supply chain (soy and cattle) and governmental actors may be crucial to reduce deforestation in the Amazon.

Year | Title
:--- | :-------------------------------------------- | 
under Review | Hissa, L.B.V., Garcia Marquez, J.R., **Gollnow, F.**, Lakes, T. Enhancing synergies for effective large-scale forest restoration in Mato Grosso, Brazilian Amazon
under Review | Hissa, L.B.V., **Gollnow, F.**, Mueller, H., Lakes, T. Land tenure diversity and forest cover change in a deforestation frontier
2019 | Hissa, L.B.V., Aguiar, A., Camargo, R., Santos de Lima, L., **Gollnow, F.**, Lakes, T. [Regrowing forests contribution to law compliance and carbon storage in private properties of the Brazilian Amazon](https://doi.org/10.1016/j.landusepol.2019.104163). Land Use Policy (88), 104-163
2018 | **Gollnow, F.**, Hissa, L.B.V., Rufin, P., Lakes, T. [Property-level direct and indirect deforestation for soybean production in the Amazon region of Mato Grosso, Brazil](https://doi.org/10.1016/j.landusepol.2018.07.010). Land Use Policy (78), 377–385
2018 | **Gollnow, F.**, [Land use change and land use displacement dynamics in Mato Grosso and Pará, Brazilian Amazon](https://doi.org/10.18452/18732), Ph.D. theses, Supervised by Prof. Tobia Lakes
2017 | **Gollnow, F.**, Göpel, J., Hissa, L.B.V., Schaldach, R., Lakes, T. [Scenarios of land-use change in a deforestation corridor in the Brazilian Amazon: Combining two scales of analysis](https://doi.org/10.1007/s10113-017-1129-1). Regional Environmental Change (18), 143–159
2017 | Schaldach, R., Meurer, K.H.E., Jungkunst, H.F., Nendel, C., Lakes, T., **Gollnow, F.**, Göpel, J., Boy, J., Guggenberger, G., Strey, R., Strey, S., Berger, T., Gerold, G., Schönenberg, R., Böhner, J., Schindewolf, M., Latynskiy, E., Hampf, A., Parker, P.S., Sentelhas, P.C. [A model-based assessment of the environmental impact of land-use change across scales in Southern Amazonia](https://doi.org/10.1007/s10113-017-1244-z). Regional Environmental Change (18), 161–173
2017 | Schönenberg, R., Goepel, J., Schaldach, R., **Gollnow, F.**, Lakes, T. [Inter- and transdisciplinary scenario construction to explore future land use options in Southern Amazonia](http://www.jstor.org/stable/26270154). Ecology and Society 22 (3)
2016 | Pinheiro, T.F., Escada, M.I.S., Valeriano, D.M., Hostert, P., **Gollnow, F.**, Müller, H. [Forest Degradation Associated with Logging Frontier Expansion in the Amazon: The BR-163 Region in Southwestern Pará, Brazil](https://doi.org/10.1175/EI-D-15-0016.1). Earth Interactions 20 (17), 1–26
2014 | **Gollnow, F.**, Lakes, T. [Policy change, land use, and agriculture: The case of soy production and cattle ranching in Brazil, 2001 - 2012](https://doi.org/10.1016/j.apgeog.2014.09.003). Applied Geography (55), 203–211

\

### Fun project contributions on human environmental interactions

Year | Title
:--- | :-------------------------------------------- | 
submitted | Enoguanbhor, E.C., **Gollnow, F.**, Walker, B.B. , Nielsen, J.O., Lakes, T. Key challenges for land use planning strategies and their environmental assessments in the Abuja city-region, Nigeria  
2021 | Vijay V., Field, C.R, **Gollnow, F.**, Jones, K.K. [Using internet search data to understand information seeking behavior for health and conservation topics during the COVID-19 pandemic](https://doi.org/10.1016/j.biocon.2021.109078), Biological Conservation 
2020 | Enoguanbhor, E.C., **Gollnow, F.**, Walker, B.B. , Nielsen, J.O., Lakes, T. [Simulating urban land expansion in the context of land use planning in the Abuja city-region, Nigeria](https://doi.org/10.1007/s10708-020-10317-x). Geojournal 
2019 | Enoguanbhor, E.C., **Gollnow, F.**, Nielsen, J.O., Lakes, T., Walker, B.B. [Land Cover Change in the Abuja City-Region, Nigeria: Integrating GIS and Remotely Sensed Data to Support Land Use Planning](https://dx.doi.org/10.3390/su11051313). Sustainability (11), 1313
2019 | Rufin, P., **Gollnow, F.**, Müller, D., Hostert, P. [Synthesizing dam-induced land system change](https://doi.org/10.1007/s13280-018-01144-z). Ambio 48(10), 1183-1194
2018 | Schägner, J.P., Brander, L., Paracchini, M.L., Maes, J., **Gollnow, F.**, Bertzky, B. [Spatial dimensions of recreational ecosystem service values: A review of meta-analyses and a combination of meta-analytic value-transfer and GIS](https://doi.org/10.1016/j.ecoser.2018.03.003). Ecosystem Services (31), 395–409





